# base image
FROM cgr.dev/ky-rafaels.example.com/python:3.11-dev AS builder

# for easy upgrade later. ARG variables only persist during image build time
ARG PHX_VER="2.0.0"

WORKDIR /app

USER root

# install dependencies (pigz needed for nf-core modules, bc and rsync needed for post gamma steps in PHoeNIx)
RUN apk add --no-cache \
    readline-dev \
    llvm \ 
    ncurses-dev \
    busybox \
    tk-dev \ 
    # liblzma-dev \
    bc \ 
    pigz \
    rsync \
    unzip \
    # tar \
    gzip 

#install biopython and other required modules
RUN pip3 install --no-cache-dir biopython \
    glob2 \
    argparse \
    unidecode \
    pandas \
    numpy \
    regex \
    times \
    xlsxwriter \
    # cryptography==36.0.2 \
    cryptography \
    pytest-shutil \
    openpyxl --target=/app/deps

FROM cgr.dev/ky-rafaels.example.com/python:3.11-dev 

ARG PHX_VER="2.0.0"

LABEL base.image="cgr.dev/ky-rafaels.example.com/python:3.11-dev"
LABEL dockerfile.version="2"
LABEL software="PhoeNIx"
LABEL software.version="v2.0.0"
LABEL description="Basic Linux for Running PHoeNIx bash scripts"
LABEL website="https://github.com/cdcgov/phoenix"
LABEL license="Apache 2.0"
LABEL maintainer="Kyle Rafaels"
LABEL maintainer.email="kyle.rafaels@chainguard.dev"

WORKDIR /app

COPY --from=builder /app/deps /app/deps

ENV PYTHONPATH=/app/deps